const productsList = [
  {
    id_product: 1,
    category: "eletronica",
    fk_idcategorys: 1,
    name_product: "Microcontrolador",
    price: 30,
    image: "./images/produtos/microcontrolador.webp",
    id_categorys: 1,
    name_categorys: "Microcontrolador",
    selected: false,
  },
  {
    id_product: 2,
    category: "eletronica",
    fk_idcategorys: 1,
    name_product: "Arduino Mega",
    price: 270,
    image: "./images/produtos/mega.jpg",
    id_categorys: 1,
    name_categorys: "Arduino",
    selected: false,
  },
  {
    id_product: 9,
    category: "eletronica",
    fk_idcategorys: 1,
    name_product: "Display LCD 16x2 ",
    price: 40,
    image: "./images/produtos/display.jpg",
    id_categorys: 1,
    name_categorys: "Para sua bancada",
    selected: false,
  },
  {
    id_product: 4,
    category: "eletronica",
    fk_idcategorys: 2,
    name_product: "HK-915 - Bivolt Hikari",
    price: 899.99,
    image: "./images/produtos/est.jpg",
    id_categorys: 1,
    name_categorys: "Para sua bancada",
    selected: false,
  },
  {
    id_product: 10,
    category: "eletronica",
    fk_idcategorys: 2,
    name_product: "Osciloscópio Digital",
    price: 4000,
    image: "./images/produtos/osc.jpg",
    id_categorys: 1,
    name_categorys: "Para sua bancada",
    selected: false,
  },
  {
    id_product: 11,
    category: "eletronica",
    fk_idcategorys: 2,
    name_product: "Multímetro Digital",
    price: 100.97,
    image: "./images/produtos/mult.jpg",
    id_categorys: 1,
    name_categorys: "Para sua bancada",
    selected: false,
  },
  {
    id_product: 6,
    category: "eletronica",
    fk_idcategorys: 3,
    name_product: "Kit para Arduino",
    price: 200,
    image: "./images/produtos/kit-arduino.jpg",
    id_categorys: 1,
    name_categorys: "Arduino",
    selected: false,
  },
  {
    id_product: 7,
    category: "eletronica",
    fk_idcategorys: 3,
    name_product: "Arduino Uno R3",
    price: 120,
    image: "./images/produtos/uno.webp",
    id_categorys: 1,
    name_categorys: "Arduino",
    selected: false,
  },
];

export default productsList;
